version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://1.214.89.64:4100/core/dashboard
    ports:
      - "4333:3000"
    environment:
      - NODE_ENV=production
    restart: always
